version = 1
SPDX-PackageName = "SAP-docs/btp-cloud-logging"
SPDX-PackageSupplier = "Maksimiliana Petrova (maksimiliana.petrova@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-cloud-logging"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2024 SAP SE or an SAP affiliate company and SAP-docs/btp-cloud-logging contributors"
SPDX-License-Identifier = "CC-BY-4.0"
